name: exploring-level-p
version: 0.1.0.0
github: "Riddarvid/exploring-level-p"
license: BSD-3-Clause
author: "Riddarvid"
maintainer: "code@arvid-rydberg.se"
copyright: "2024 Riddarvid"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/BoFunComplexitySubclasses#readme>

dependencies:
  - base >= 4.13 && < 4.19
  - containers >= 0.6.7
  - decision-diagrams >= 0.2.0.0
  - multiset >= 0.3.4.3
  - memoize >= 1.1
  - mtl >= 2.2
  - free >= 5.1.10

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  exploring-level-p-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - exploring-level-p

tests:
  exploring-level-p-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - exploring-level-p
